# Generated by Django 5.2.7 on 2025-10-24 20:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.URLField(blank=True, max_length=300)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^(\\+91)?\\d{10}$')])),
                ('industry', models.CharField(blank=True, choices=[('', '---------'), ('TECH', 'Technology'), ('FIN', 'Finance'), ('HEALTH', 'Healthcare'), ('MANU', 'Manufacturing'), ('RETAIL', 'Retail/E-commerce'), ('PROF_SVC', 'Professional Services'), ('EDU', 'Education'), ('ENERGY', 'Energy'), ('TRANS', 'Transportation & Logistics'), ('REALEST', 'Real Estate & Construction'), ('HOSP', 'Hospitality'), ('MEDIA', 'Media & Entertainment'), ('AGRI', 'Agriculture'), ('NONPROF', 'Non-Profit'), ('GOV', 'Government'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^(\\+91)?\\d{10}$')])),
                ('role', models.CharField(choices=[('ADMIN', 'Company Admin'), ('MEMBER', 'Employee Member')], default='MEMBER', max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
